services:
  currency-exchange:
    image: selintopcu/mvv2-currency-exchange:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
  currency-conversion:
    image: selintopcu/mvv2-currency-conversion:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: selintopcu/mvv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: selintopcu/mvv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always
  rabbitmq:
    image: rabbitmq:latest
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network:
